use CustomerDB;

SELECT * FROM customers;

Alter table customers
alter column purchase_amount FLOAT;

EXEC sp_help customers;

--What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount) FROM customers
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id FROM customers 
WHERE discount_applied = 'Yes' and purchase_amount > (SELECT ROUND(AVG(purchase_amount),2) FROM customers);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5 item_purchased, ROUND(avg(review_rating),2) FROM customers 
GROUP BY item_purchased
ORDER BY avg(review_rating) desc;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT ROUND(AVG(purchase_amount),2) as avg_purchase_amount,shipping_type FROM customers
GROUP BY shipping_type
HAVING shipping_type in ('Standard','Express');

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, ROUND(AVG(purchase_amount),2) Avg_revenue, sum(purchase_amount) Total_revenue FROM customers
GROUP BY subscription_status;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5 item_purchased,ROUND(100.00 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC;


--Q7. Segment customers into New, Returning, and Loyal based on their total  number of previous purchases, and show the count of each segment. 

WITH cte AS(
	SELECT customer_id,
	CASE 
		WHEN previous_purchases = 1 THEN 'new'
		WHEN previous_purchases between 2 and 10 THEN 'returning'
		WHEN previous_purchases > 10 THEN 'loyal'
	END AS seg_type FROM customers
)
SELECT count(*) TotalCount,seg_type FROM cte
GROUP BY seg_type;


--Q8. What are the top 3 most purchased products within each category? 

WITH cte AS(
	SELECT
	COUNT(customer_id) AS countt,
	category,
	item_purchased,
	ROW_NUMBER() OVER(PARTITION BY category ORDER BY count(customer_id) DESC) AS rn FROM customers GROUP BY category,item_purchased 
)
SELECT item_purchased, category,countt FROM cte WHERE rn <=3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status, count(*) FROM customers WHERE previous_purchases > 5 
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group? 

SELECT age_group,SUM(purchase_amount) total_revenue FROM customers
GROUP BY age_group;

--Q11. Top 5 locations that generate more revenue
SELECT TOP 5 location, SUM(purchase_amount) revenue
FROM customers
GROUP BY location
ORDER BY revenue DESC;


--Q12.Payment methods that customer use
SELECT payment_method,
	ROUND(AVG(purchase_amount),2) Avg_PurchaseAmount,
	SUM(purchase_amount) Sum_PurchaseAmount
FROM customers
GROUP BY payment_method;